# Generated by Django 3.0.6 on 2022-11-17 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Communications', '0001_initial'),
        ('Orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderchat',
            name='chain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Orders.OrderChain'),
        ),
    ]
