# Generated by Django 3.0.6 on 2022-11-27 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Communications', '0003_auto_20221117_1306'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatmessage',
            options={'ordering': ['-sent_at']},
        ),
    ]
