version: '3.3'
services:
  backend_container:
    container_name: backend_container
    restart: always
    build: .
    ports:
      - "127.0.0.1:7000:7000"
    volumes:
      - .:/app/code
#  search:
#    image: "getmeili/meilisearch:latest"
#    container_name: search
#    restart: always
#    ports:
#      - "7700:7700"
#    volumes:
#      - "../search/data.ms:/data.ms"
#    environment:
#      - SCOUT_DRIVER=meilisearch
#      - MEILISEARCH_HOST=http://meilisearch:7700
#      - MEILISEARCH_KEY=masterKey
#      - MEILI_MASTER_KEY=MEILI_awdbjhadHADdnakwdnkja
#    healthcheck:
#      test: ["CMD", "wget", "--no-verbose", "--spider",  "http://meilisearch:7700/health"]
#      retries: 3
#      timeout: 5s
  nginx:
    container_name: nginx
    restart: always
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./APIBackendService/web:/etc/nginx/html
      - ./APIBackendService/static:/etc/nginx/html/static
    ports:
      - "8080:8080"
    depends_on:
      - backend_container
#      - search