# Generated by Django 3.0.6 on 2022-11-17 10:06

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, default='', max_length=12, null=True)),
                ('balance', models.IntegerField(blank=True, default=0, null=True)),
                ('inn', models.CharField(blank=True, max_length=20, null=True, verbose_name='ИНН/КПП')),
                ('ogrn', models.CharField(blank=True, max_length=13, null=True, verbose_name='ОГРН')),
                ('okpo', models.IntegerField(blank=True, null=True, verbose_name='ОКПО')),
                ('checking_account', models.CharField(blank=True, max_length=20, null=True, verbose_name='Р/с')),
                ('correspondent_account', models.CharField(blank=True, max_length=20, null=True, verbose_name='Корреспондентский счет')),
                ('bik', models.CharField(blank=True, max_length=9, null=True, verbose_name='БИК')),
                ('leaders', jsonfield.fields.JSONField(default=[])),
                ('website', models.CharField(blank=True, max_length=180, null=True, verbose_name="Company's website")),
                ('single_factory', models.BooleanField(default=False, verbose_name='Company has only one factory')),
                ('company_type', models.IntegerField(choices=[(1, 'Provider'), (2, 'Customer'), (3, 'Transport company'), (4, 'Distributor')])),
                ('rating', models.FloatField(default=0.0)),
                ('postal_code', models.IntegerField(blank=True, null=True)),
                ('x_coordinate', models.FloatField(blank=True, null=True)),
                ('y_coordinate', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CompanyAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(default='', max_length=50, verbose_name='Страна')),
                ('post_code', models.CharField(default='', max_length=10, verbose_name='Почтовый индекс')),
                ('region', models.CharField(default='', max_length=70, verbose_name='Область')),
                ('city', models.CharField(default='', max_length=40, verbose_name='Город')),
                ('street', models.CharField(default='', max_length=70, verbose_name='Улица')),
                ('house', models.CharField(default='', max_length=20, verbose_name='Дом')),
                ('office', models.CharField(default='', max_length=80, verbose_name='Офис')),
            ],
        ),
        migrations.CreateModel(
            name='CompanyAuthToken',
            fields=[
                ('key', models.CharField(max_length=60, primary_key=True, serialize=False, verbose_name='Key')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('expired', models.DateTimeField(blank=True, null=True, verbose_name='Expired')),
            ],
            options={
                'verbose_name': 'Company auth token',
                'verbose_name_plural': 'Company auth tokens',
            },
        ),
        migrations.CreateModel(
            name='CompanyFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=300, verbose_name='Link to file')),
                ('name', models.CharField(blank=True, max_length=50, verbose_name='File name')),
                ('description', models.CharField(blank=True, max_length=300, verbose_name='File description')),
            ],
        ),
        migrations.CreateModel(
            name='CompanyProducer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('inn', models.CharField(blank=True, max_length=20, null=True, verbose_name='ИНН/КПП')),
            ],
        ),
        migrations.CreateModel(
            name='Factory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Factory name')),
                ('description', models.CharField(blank=True, max_length=8000)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.CharField(blank=True, max_length=300, null=True, verbose_name='Factory address')),
                ('website', models.CharField(blank=True, max_length=180, null=True, verbose_name="Factory's website")),
                ('rating', models.FloatField(default=0.0)),
                ('postal_code', models.IntegerField(blank=True, null=True)),
                ('x_coordinate', models.FloatField(blank=True, null=True)),
                ('y_coordinate', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FactoryCompanyRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('factory_confirmed', models.NullBooleanField()),
                ('company_confirmed', models.NullBooleanField()),
                ('verified', models.NullBooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='FactoryProducer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Okved',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('code', models.CharField(max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrganizationsRelationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship_type', models.IntegerField(choices=[(1, 'Ownership'), (2, 'Partnership'), (3, 'Transportation'), (4, 'Distribution'), (5, 'Banned')], verbose_name='Type of relationship')),
                ('company_1_confirmed', models.NullBooleanField()),
                ('company_2_confirmed', models.NullBooleanField()),
                ('verified', models.NullBooleanField()),
                ('verified_datetime', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrganizationsRelationshipFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=300, verbose_name='Link to file')),
                ('name', models.CharField(blank=True, max_length=50, verbose_name='File name')),
                ('description', models.CharField(blank=True, max_length=300, verbose_name='File description')),
            ],
        ),
        migrations.CreateModel(
            name='TokenInviteOtherCompany',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=40)),
                ('email_to_invite', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('used', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postal_code', models.IntegerField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=300, null=True, verbose_name='Warehouse address')),
                ('x_coordinate', models.FloatField(blank=True, null=True)),
                ('y_coordinate', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WarehouseCompanyRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Organizations.Company')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Organizations.Warehouse')),
            ],
        ),
        migrations.CreateModel(
            name='TokenInviteToCompany',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=40)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Organizations.Company')),
            ],
        ),
    ]
