# Generated by Django 3.0.6 on 2022-11-17 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Organizations', '0002_auto_20221117_1306'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyaddress',
            name='company',
        ),
    ]
