# Generated by Django 3.0.6 on 2022-11-17 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Organizations', '0003_remove_companyaddress_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='okved',
            field=models.ManyToManyField(to='Organizations.Okved', verbose_name='ОКВЭД'),
        ),
    ]
