# Generated by Django 3.0.6 on 2022-11-19 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Organizations', '0004_auto_20221117_1705'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(default='', max_length=50, verbose_name='Страна')),
                ('post_code', models.CharField(default='', max_length=10, verbose_name='Почтовый индекс')),
                ('region', models.CharField(default='', max_length=70, verbose_name='Область')),
                ('city', models.CharField(default='', max_length=40, verbose_name='Город')),
                ('street', models.CharField(default='', max_length=70, verbose_name='Улица')),
                ('house', models.CharField(default='', max_length=20, verbose_name='Дом')),
                ('office', models.CharField(default='', max_length=80, verbose_name='Офис')),
            ],
        ),
        migrations.AlterField(
            model_name='company',
            name='legal_address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='legal_address', to='Organizations.Address', verbose_name='Юридический адрес'),
        ),
        migrations.AlterField(
            model_name='company',
            name='physical_address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='physical_address', to='Organizations.Address'),
        ),
        migrations.DeleteModel(
            name='CompanyAddress',
        ),
    ]
