# Generated by Django 3.0.6 on 2022-11-19 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Documents', '0004_auto_20221119_1718'),
        ('Organizations', '0005_auto_20221119_1151'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyfile',
            name='description',
        ),
        migrations.RemoveField(
            model_name='companyfile',
            name='link',
        ),
        migrations.RemoveField(
            model_name='companyfile',
            name='name',
        ),
        migrations.AddField(
            model_name='companyfile',
            name='document',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Documents.Document'),
        ),
        migrations.AlterField(
            model_name='companyfile',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Organizations.Company'),
        ),
        migrations.AlterField(
            model_name='organizationsrelationshipfile',
            name='relation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Organizations.OrganizationsRelationship'),
        ),
    ]
