# Generated by Django 3.0.6 on 2022-11-19 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Organizations', '0009_auto_20221120_0033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='company_type',
            field=models.IntegerField(choices=[(1, 'Provider'), (2, 'Transport company'), (3, 'Distributor')]),
        ),
    ]
