# Generated by Django 3.0.6 on 2022-11-17 10:06

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.PositiveSmallIntegerField(choices=[(0, 'Create_excel_table_from_products'), (1, 'Other')], default=1)),
                ('token', models.CharField(max_length=10, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Waiting'), (4, 'In progress'), (2, 'Finished'), (3, 'Rejected')], default=1)),
                ('data', jsonfield.fields.JSONField(default=dict)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('progress', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
    ]
