# Generated by Django 3.0.6 on 2022-11-19 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Documents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='description',
            field=models.CharField(blank=True, max_length=4000),
        ),
        migrations.AlterField(
            model_name='document',
            name='link',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='document',
            name='name',
            field=models.CharField(max_length=150),
        ),
    ]
