# Generated by Django 3.0.6 on 2022-11-17 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrderChain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(blank=True, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('status', models.IntegerField(choices=[(0, 'Reject'), (1, 'Waiting'), (2, 'Confirmed'), (3, 'Completed')], default=1)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('comment', models.CharField(blank=True, max_length=4000)),
            ],
        ),
        migrations.CreateModel(
            name='ProductRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_time', models.DateTimeField(auto_now_add=True)),
                ('request', models.CharField(max_length=200)),
                ('amount', models.PositiveIntegerField(default=1)),
                ('description', models.CharField(blank=True, max_length=4000, null=True)),
                ('preferable_time', models.DateTimeField(blank=True, null=True)),
                ('preferable_price', models.IntegerField(blank=True, null=True)),
                ('delivery_type', models.IntegerField(choices=[(1, 'On factory'), (2, 'By address'), (3, 'Contact later')])),
                ('address', models.CharField(blank=True, max_length=300)),
                ('status', models.IntegerField(choices=[(0, 'HISTORY'), (1, 'CONSTRUCTION'), (2, 'ACTIVE')], default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ProductRequestImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=300, verbose_name='Link to image')),
                ('description', models.CharField(blank=True, max_length=300, verbose_name='Image description')),
                ('request', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Orders.ProductRequest')),
            ],
        ),
        migrations.CreateModel(
            name='ProductRequestFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=300, verbose_name='Link to file')),
                ('name', models.CharField(blank=True, max_length=50, verbose_name='File name')),
                ('description', models.CharField(blank=True, max_length=300, verbose_name='File description')),
                ('request', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Orders.ProductRequest')),
            ],
        ),
    ]
