# Generated by Django 3.0.6 on 2022-11-17 10:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Orders', '0003_productrequest_product'),
        ('Organizations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productrequest',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orderchain',
            name='company_executor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_executor', to='Organizations.Company'),
        ),
        migrations.AddField(
            model_name='orderchain',
            name='factory_executor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='factory_executor', to='Organizations.Factory'),
        ),
        migrations.AddField(
            model_name='orderchain',
            name='product_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Orders.ProductRequest'),
        ),
        migrations.AddField(
            model_name='orderchain',
            name='transport_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transport_company', to='Organizations.Company'),
        ),
    ]
