# Generated by Django 3.0.6 on 2022-11-17 10:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Orders', '0003_productrequest_product'),
        ('Organizations', '0001_initial'),
        ('Notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usernotification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='telegrammessage',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='organizationsrelationshiptelegramnotification',
            name='message',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Notifications.TelegramMessage'),
        ),
        migrations.AddField(
            model_name='organizationsrelationshiptelegramnotification',
            name='relationship',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Organizations.OrganizationsRelationship'),
        ),
        migrations.AddField(
            model_name='orderchaintelegramnotification',
            name='chain',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Orders.OrderChain'),
        ),
        migrations.AddField(
            model_name='orderchaintelegramnotification',
            name='message',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Notifications.TelegramMessage'),
        ),
    ]
