# Generated by Django 3.0.6 on 2022-11-17 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='product name')),
                ('price', models.PositiveIntegerField(blank=True, verbose_name='Price in rubles')),
                ('description', models.CharField(blank=True, max_length=4000, verbose_name='Product description')),
                ('tags_text', models.CharField(blank=True, max_length=1000, verbose_name='Tags for the product')),
                ('meta_information', models.TextField(default='[]', verbose_name='JSON meta information')),
                ('condition', models.PositiveSmallIntegerField(choices=[(0, 'New'), (1, 'Used')], default=0, verbose_name='Состояние товара')),
                ('is_available', models.PositiveSmallIntegerField(choices=[(0, 'Unavailable'), (1, 'Available')], default=1, verbose_name='Наличие товара')),
            ],
        ),
        migrations.CreateModel(
            name='ProductFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=300, verbose_name='Link to file')),
                ('name', models.CharField(blank=True, max_length=50, verbose_name='File name')),
                ('description', models.CharField(blank=True, max_length=300, verbose_name='File description')),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=300, verbose_name='Link to image')),
                ('description', models.CharField(blank=True, max_length=300, verbose_name='Image description')),
            ],
        ),
        migrations.CreateModel(
            name='ProductRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(choices=[(None, '-'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=None, null=True)),
                ('description', models.CharField(blank=True, max_length=700, null=True)),
                ('last_changed_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, verbose_name='File name')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('link', models.CharField(max_length=300, verbose_name='Link to file')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Tag name')),
                ('description', models.CharField(blank=True, max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='TagProductRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verification', models.NullBooleanField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Products.Product')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Products.Tag')),
            ],
        ),
        migrations.CreateModel(
            name='ProductsProcessingFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, verbose_name='File name')),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('link', models.CharField(max_length=300, verbose_name='Link to file')),
                ('annotation', models.CharField(blank=True, max_length=500, verbose_name='File annotation')),
                ('status', models.IntegerField(choices=[(1, 'In progress'), (2, 'Confirmed'), (3, 'Rejected')], default=1)),
                ('comment', models.CharField(blank=True, max_length=500, verbose_name='File comment')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Organizations.Company')),
                ('factory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Organizations.Factory')),
            ],
        ),
    ]
