# Generated by Django 3.0.6 on 2022-11-19 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Documents', '0004_auto_20221119_1718'),
        ('Products', '0002_auto_20221117_1306'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productfile',
            name='description',
        ),
        migrations.RemoveField(
            model_name='productfile',
            name='link',
        ),
        migrations.RemoveField(
            model_name='productfile',
            name='name',
        ),
        migrations.AddField(
            model_name='productfile',
            name='document',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Documents.Document'),
        ),
    ]
